<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="tools\extracticon.exe" />
    <None Remove="tools\ImageMagick\ChangeLog.md" />
    <None Remove="tools\ImageMagick\colors.xml" />
    <None Remove="tools\ImageMagick\configure.xml" />
    <None Remove="tools\ImageMagick\delegates.xml" />
    <None Remove="tools\ImageMagick\english.xml" />
    <None Remove="tools\ImageMagick\LICENSE.txt" />
    <None Remove="tools\ImageMagick\locale.xml" />
    <None Remove="tools\ImageMagick\log.xml" />
    <None Remove="tools\ImageMagick\magick.exe" />
    <None Remove="tools\ImageMagick\mime.xml" />
    <None Remove="tools\ImageMagick\NOTICE.txt" />
    <None Remove="tools\ImageMagick\policy.xml" />
    <None Remove="tools\ImageMagick\sRGB.icc" />
    <None Remove="tools\ImageMagick\thresholds.xml" />
    <None Remove="tools\ImageMagick\type-ghostscript.xml" />
    <None Remove="tools\ImageMagick\type.xml" />
  </ItemGroup>

  <ItemGroup>
    <COMReference Include="IWshRuntimeLibrary">
      <WrapperTool>tlbimp</WrapperTool>
      <VersionMinor>0</VersionMinor>
      <VersionMajor>1</VersionMajor>
      <Guid>f935dc20-1cf0-11d0-adb9-00c04fd58a0b</Guid>
      <Lcid>0</Lcid>
      <Isolated>false</Isolated>
      <EmbedInteropTypes>true</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="tools\extracticon.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\ChangeLog.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\colors.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\configure.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\delegates.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\english.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\LICENSE.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\locale.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\log.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\magick.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\mime.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\NOTICE.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\policy.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\sRGB.icc">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\thresholds.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\type-ghostscript.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="tools\ImageMagick\type.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

</Project>
